/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airlinereservation;

import java.awt.Desktop;

/**
 *
 * @author Naveen
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addc = new javax.swing.JMenuItem();
        searchc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addf = new javax.swing.JMenuItem();
        bookt = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        viewt = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        adda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Customer");

        addc.setText("Add Customer");
        addc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcActionPerformed(evt);
            }
        });
        jMenu1.add(addc);

        searchc.setText("Search Customer");
        searchc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcActionPerformed(evt);
            }
        });
        jMenu1.add(searchc);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Flight");

        addf.setText("Add Flight");
        addf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfActionPerformed(evt);
            }
        });
        jMenu2.add(addf);

        bookt.setText("Book Flight");
        bookt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booktActionPerformed(evt);
            }
        });
        jMenu2.add(bookt);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ticket");

        viewt.setText("View Ticket");
        viewt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewtActionPerformed(evt);
            }
        });
        jMenu3.add(viewt);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Admin");

        adda.setText("Add Admin");
        adda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaActionPerformed(evt);
            }
        });
        jMenu4.add(adda);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcActionPerformed
        // TODO add your handling code here:
        AddCustomer customer=new AddCustomer();
        Desktop.add(customer);
        customer.setVisible(true);
        
    }//GEN-LAST:event_addcActionPerformed

    private void searchcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcActionPerformed
        // TODO add your handling code here:
        SearchCustomer search=new SearchCustomer();
        Desktop.add(search);
        search.setVisible(true);
        
    }//GEN-LAST:event_searchcActionPerformed

    private void addfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfActionPerformed
        // TODO add your handling code here:
        AddFlight flight=new AddFlight();
        Desktop.add(flight);
        flight.setVisible(true);
    }//GEN-LAST:event_addfActionPerformed

    private void addaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaActionPerformed
        // TODO add your handling code here:
        AddAdmin admin=new AddAdmin();
        Desktop.add(admin);
        admin.setVisible(true);
    }//GEN-LAST:event_addaActionPerformed

    private void booktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booktActionPerformed
        // TODO add your handling code here:
        BookTicket newTicket=new BookTicket();
        Desktop.add(newTicket);
        newTicket.setVisible(true);
    }//GEN-LAST:event_booktActionPerformed

    private void viewtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewtActionPerformed
        // TODO add your handling code here:
        GetTicket ticket=new GetTicket();
        Desktop.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_viewtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem adda;
    private javax.swing.JMenuItem addc;
    private javax.swing.JMenuItem addf;
    private javax.swing.JMenuItem bookt;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem searchc;
    private javax.swing.JMenuItem viewt;
    // End of variables declaration//GEN-END:variables
}
